# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Maintenance_design_osh.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1106, 774)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(640, 360))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.setMouseTracking(True)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icons8-support-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(0.95)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: qconicalgradient(cx:0.403, cy:1, angle:0, stop:0.448864 rgba(16, 100, 158, 241), stop:1 rgba(255, 255, 255, 255));\n"
"border-top-color: rgb(42, 106, 255);\n"
"border-color: rgb(0, 156, 0);\n"
"")
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.timedate = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timedate.sizePolicy().hasHeightForWidth())
        self.timedate.setSizePolicy(sizePolicy)
        self.timedate.setMinimumSize(QtCore.QSize(300, 25))
        self.timedate.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.timedate.setFont(font)
        self.timedate.setStyleSheet("color: rgb(26, 255, 14);")
        self.timedate.setFrameShape(QtWidgets.QFrame.Box)
        self.timedate.setText("")
        self.timedate.setObjectName("timedate")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.timedate)
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.btn = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn.sizePolicy().hasHeightForWidth())
        self.btn.setSizePolicy(sizePolicy)
        self.btn.setMinimumSize(QtCore.QSize(20, 25))
        self.btn.setMaximumSize(QtCore.QSize(50, 50))
        self.btn.setCheckable(True)
        self.btn.setObjectName("btn")
        self.horizontalLayout_1.addWidget(self.btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem2)
        self.terminal = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminal.sizePolicy().hasHeightForWidth())
        self.terminal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.terminal.setFont(font)
        self.terminal.setCheckable(False)
        self.terminal.setAutoDefault(False)
        self.terminal.setObjectName("terminal")
        self.horizontalLayout_1.addWidget(self.terminal)
        spacerItem3 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem3)
        self.start = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.start.setFont(font)
        self.start.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"gridline-color: rgb(0, 85, 255);\n"
"selection-color: rgb(85, 170, 0);")
        self.start.setObjectName("start")
        self.horizontalLayout_1.addWidget(self.start)
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit.sizePolicy().hasHeightForWidth())
        self.exit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.exit.setFont(font)
        self.exit.setStyleSheet("background-color: qconicalgradient(cx:0.914773, cy:0.79, angle:0, stop:0.164773 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: qconicalgradient(cx:1, cy:0.329773, angle:0, stop:0.164773 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.exit.setObjectName("exit")
        self.horizontalLayout_1.addWidget(self.exit)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.SpanningRole, spacerItem4)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.visV5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visV5.sizePolicy().hasHeightForWidth())
        self.visV5.setSizePolicy(sizePolicy)
        self.visV5.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.visV5.setFont(font)
        self.visV5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.visV5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.visV5.setTextFormat(QtCore.Qt.AutoText)
        self.visV5.setScaledContents(True)
        self.visV5.setAlignment(QtCore.Qt.AlignCenter)
        self.visV5.setObjectName("visV5")
        self.gridLayout_4.addWidget(self.visV5, 9, 4, 1, 1)
        self.windV1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windV1.sizePolicy().hasHeightForWidth())
        self.windV1.setSizePolicy(sizePolicy)
        self.windV1.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.windV1.setFont(font)
        self.windV1.setStatusTip("")
        self.windV1.setWhatsThis("")
        self.windV1.setAccessibleName("")
        self.windV1.setAccessibleDescription("")
        self.windV1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.windV1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.windV1.setTextFormat(QtCore.Qt.AutoText)
        self.windV1.setScaledContents(True)
        self.windV1.setAlignment(QtCore.Qt.AlignCenter)
        self.windV1.setObjectName("windV1")
        self.gridLayout_4.addWidget(self.windV1, 0, 2, 1, 1)
        self.windV2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windV2.sizePolicy().hasHeightForWidth())
        self.windV2.setSizePolicy(sizePolicy)
        self.windV2.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.windV2.setFont(font)
        self.windV2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.windV2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.windV2.setTextFormat(QtCore.Qt.AutoText)
        self.windV2.setScaledContents(True)
        self.windV2.setAlignment(QtCore.Qt.AlignCenter)
        self.windV2.setObjectName("windV2")
        self.gridLayout_4.addWidget(self.windV2, 0, 6, 1, 1)
        self.cldV3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cldV3.sizePolicy().hasHeightForWidth())
        self.cldV3.setSizePolicy(sizePolicy)
        self.cldV3.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.cldV3.setFont(font)
        self.cldV3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cldV3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cldV3.setTextFormat(QtCore.Qt.AutoText)
        self.cldV3.setScaledContents(True)
        self.cldV3.setAlignment(QtCore.Qt.AlignCenter)
        self.cldV3.setObjectName("cldV3")
        self.gridLayout_4.addWidget(self.cldV3, 6, 0, 1, 1)
        self.cldV2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cldV2.sizePolicy().hasHeightForWidth())
        self.cldV2.setSizePolicy(sizePolicy)
        self.cldV2.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.cldV2.setFont(font)
        self.cldV2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cldV2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cldV2.setTextFormat(QtCore.Qt.AutoText)
        self.cldV2.setScaledContents(True)
        self.cldV2.setAlignment(QtCore.Qt.AlignCenter)
        self.cldV2.setObjectName("cldV2")
        self.gridLayout_4.addWidget(self.cldV2, 5, 8, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 7, 4, 1, 1)
        self.infoLn1 = QtWidgets.QLabel(self.centralwidget)
        self.infoLn1.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.infoLn1.setFont(font)
        self.infoLn1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.infoLn1.setText("")
        self.infoLn1.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLn1.setObjectName("infoLn1")
        self.gridLayout_4.addWidget(self.infoLn1, 6, 2, 1, 5)
        spacerItem6 = QtWidgets.QSpacerItem(80, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 2, 5, 1, 1)
        self.visV2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visV2.sizePolicy().hasHeightForWidth())
        self.visV2.setSizePolicy(sizePolicy)
        self.visV2.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.visV2.setFont(font)
        self.visV2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.visV2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.visV2.setTextFormat(QtCore.Qt.AutoText)
        self.visV2.setScaledContents(True)
        self.visV2.setAlignment(QtCore.Qt.AlignCenter)
        self.visV2.setObjectName("visV2")
        self.gridLayout_4.addWidget(self.visV2, 8, 4, 1, 1)
        self.cldV4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cldV4.sizePolicy().hasHeightForWidth())
        self.cldV4.setSizePolicy(sizePolicy)
        self.cldV4.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.cldV4.setFont(font)
        self.cldV4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cldV4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cldV4.setTextFormat(QtCore.Qt.AutoText)
        self.cldV4.setScaledContents(True)
        self.cldV4.setAlignment(QtCore.Qt.AlignCenter)
        self.cldV4.setObjectName("cldV4")
        self.gridLayout_4.addWidget(self.cldV4, 6, 8, 1, 1)
        self.tempV2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempV2.sizePolicy().hasHeightForWidth())
        self.tempV2.setSizePolicy(sizePolicy)
        self.tempV2.setMinimumSize(QtCore.QSize(120, 30))
        self.tempV2.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.tempV2.setFont(font)
        self.tempV2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tempV2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tempV2.setTextFormat(QtCore.Qt.AutoText)
        self.tempV2.setScaledContents(True)
        self.tempV2.setAlignment(QtCore.Qt.AlignCenter)
        self.tempV2.setObjectName("tempV2")
        self.gridLayout_4.addWidget(self.tempV2, 0, 8, 1, 1, QtCore.Qt.AlignRight)
        self.windV3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windV3.sizePolicy().hasHeightForWidth())
        self.windV3.setSizePolicy(sizePolicy)
        self.windV3.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.windV3.setFont(font)
        self.windV3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.windV3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.windV3.setTextFormat(QtCore.Qt.AutoText)
        self.windV3.setScaledContents(True)
        self.windV3.setAlignment(QtCore.Qt.AlignCenter)
        self.windV3.setObjectName("windV3")
        self.gridLayout_4.addWidget(self.windV3, 2, 2, 1, 1)
        self.mk2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mk2.sizePolicy().hasHeightForWidth())
        self.mk2.setSizePolicy(sizePolicy)
        self.mk2.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.mk2.setFont(font)
        self.mk2.setStyleSheet("background-color: rgb(148, 148, 148);\n"
"")
        self.mk2.setTextFormat(QtCore.Qt.RichText)
        self.mk2.setAlignment(QtCore.Qt.AlignCenter)
        self.mk2.setObjectName("mk2")
        self.gridLayout_4.addWidget(self.mk2, 5, 6, 1, 1, QtCore.Qt.AlignLeft)
        self.visV6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visV6.sizePolicy().hasHeightForWidth())
        self.visV6.setSizePolicy(sizePolicy)
        self.visV6.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.visV6.setFont(font)
        self.visV6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.visV6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.visV6.setTextFormat(QtCore.Qt.AutoText)
        self.visV6.setScaledContents(True)
        self.visV6.setAlignment(QtCore.Qt.AlignCenter)
        self.visV6.setObjectName("visV6")
        self.gridLayout_4.addWidget(self.visV6, 9, 6, 1, 1)
        self.windV4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windV4.sizePolicy().hasHeightForWidth())
        self.windV4.setSizePolicy(sizePolicy)
        self.windV4.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.windV4.setFont(font)
        self.windV4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.windV4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.windV4.setTextFormat(QtCore.Qt.AutoText)
        self.windV4.setScaledContents(True)
        self.windV4.setAlignment(QtCore.Qt.AlignCenter)
        self.windV4.setObjectName("windV4")
        self.gridLayout_4.addWidget(self.windV4, 2, 6, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(80, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem7, 2, 3, 1, 1)
        self.mk1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mk1.sizePolicy().hasHeightForWidth())
        self.mk1.setSizePolicy(sizePolicy)
        self.mk1.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.mk1.setFont(font)
        self.mk1.setStyleSheet("background-color: rgb(148, 148, 148);")
        self.mk1.setTextFormat(QtCore.Qt.RichText)
        self.mk1.setAlignment(QtCore.Qt.AlignCenter)
        self.mk1.setObjectName("mk1")
        self.gridLayout_4.addWidget(self.mk1, 5, 2, 1, 1, QtCore.Qt.AlignRight)
        self.cldV1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cldV1.sizePolicy().hasHeightForWidth())
        self.cldV1.setSizePolicy(sizePolicy)
        self.cldV1.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.cldV1.setFont(font)
        self.cldV1.setAutoFillBackground(False)
        self.cldV1.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.cldV1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cldV1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cldV1.setTextFormat(QtCore.Qt.AutoText)
        self.cldV1.setScaledContents(True)
        self.cldV1.setAlignment(QtCore.Qt.AlignCenter)
        self.cldV1.setObjectName("cldV1")
        self.gridLayout_4.addWidget(self.cldV1, 5, 0, 1, 1)
        self.infoLn2 = QtWidgets.QLabel(self.centralwidget)
        self.infoLn2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.infoLn2.setFont(font)
        self.infoLn2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.infoLn2.setText("")
        self.infoLn2.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLn2.setObjectName("infoLn2")
        self.gridLayout_4.addWidget(self.infoLn2, 5, 3, 1, 3)
        self.visV4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visV4.sizePolicy().hasHeightForWidth())
        self.visV4.setSizePolicy(sizePolicy)
        self.visV4.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.visV4.setFont(font)
        self.visV4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.visV4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.visV4.setTextFormat(QtCore.Qt.AutoText)
        self.visV4.setScaledContents(True)
        self.visV4.setAlignment(QtCore.Qt.AlignCenter)
        self.visV4.setObjectName("visV4")
        self.gridLayout_4.addWidget(self.visV4, 9, 2, 1, 1)
        self.visV3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visV3.sizePolicy().hasHeightForWidth())
        self.visV3.setSizePolicy(sizePolicy)
        self.visV3.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.visV3.setFont(font)
        self.visV3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.visV3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.visV3.setTextFormat(QtCore.Qt.AutoText)
        self.visV3.setScaledContents(True)
        self.visV3.setAlignment(QtCore.Qt.AlignCenter)
        self.visV3.setObjectName("visV3")
        self.gridLayout_4.addWidget(self.visV3, 8, 6, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 3, 4, 1, 1)
        self.visV1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visV1.sizePolicy().hasHeightForWidth())
        self.visV1.setSizePolicy(sizePolicy)
        self.visV1.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.visV1.setFont(font)
        self.visV1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.visV1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.visV1.setTextFormat(QtCore.Qt.AutoText)
        self.visV1.setScaledContents(True)
        self.visV1.setAlignment(QtCore.Qt.AlignCenter)
        self.visV1.setObjectName("visV1")
        self.gridLayout_4.addWidget(self.visV1, 8, 2, 1, 1)
        self.tempV1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempV1.sizePolicy().hasHeightForWidth())
        self.tempV1.setSizePolicy(sizePolicy)
        self.tempV1.setMinimumSize(QtCore.QSize(120, 30))
        self.tempV1.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.tempV1.setFont(font)
        self.tempV1.setStatusTip("")
        self.tempV1.setWhatsThis("")
        self.tempV1.setAccessibleName("")
        self.tempV1.setAccessibleDescription("")
        self.tempV1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tempV1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tempV1.setTextFormat(QtCore.Qt.AutoText)
        self.tempV1.setScaledContents(True)
        self.tempV1.setAlignment(QtCore.Qt.AlignCenter)
        self.tempV1.setObjectName("tempV1")
        self.gridLayout_4.addWidget(self.tempV1, 0, 0, 1, 1)
        self.presV1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.presV1.sizePolicy().hasHeightForWidth())
        self.presV1.setSizePolicy(sizePolicy)
        self.presV1.setMinimumSize(QtCore.QSize(120, 30))
        self.presV1.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.presV1.setFont(font)
        self.presV1.setStatusTip("")
        self.presV1.setWhatsThis("")
        self.presV1.setAccessibleName("")
        self.presV1.setAccessibleDescription("")
        self.presV1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.presV1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.presV1.setTextFormat(QtCore.Qt.AutoText)
        self.presV1.setScaledContents(True)
        self.presV1.setAlignment(QtCore.Qt.AlignCenter)
        self.presV1.setObjectName("presV1")
        self.gridLayout_4.addWidget(self.presV1, 2, 0, 1, 1)
        self.presV2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.presV2.sizePolicy().hasHeightForWidth())
        self.presV2.setSizePolicy(sizePolicy)
        self.presV2.setMinimumSize(QtCore.QSize(120, 30))
        self.presV2.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.presV2.setFont(font)
        self.presV2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.presV2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.presV2.setTextFormat(QtCore.Qt.AutoText)
        self.presV2.setScaledContents(True)
        self.presV2.setAlignment(QtCore.Qt.AlignCenter)
        self.presV2.setObjectName("presV2")
        self.gridLayout_4.addWidget(self.presV2, 2, 8, 1, 1, QtCore.Qt.AlignRight)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.visM5 = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visM5.sizePolicy().hasHeightForWidth())
        self.visM5.setSizePolicy(sizePolicy)
        self.visM5.setMinimumSize(QtCore.QSize(20, 30))
        self.visM5.setMaximumSize(QtCore.QSize(50, 50))
        self.visM5.setCheckable(True)
        self.visM5.setObjectName("visM5")
        self.gridLayout_2.addWidget(self.visM5, 10, 7, 1, 1)
        self.visM6 = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visM6.sizePolicy().hasHeightForWidth())
        self.visM6.setSizePolicy(sizePolicy)
        self.visM6.setMinimumSize(QtCore.QSize(20, 30))
        self.visM6.setMaximumSize(QtCore.QSize(50, 50))
        self.visM6.setCheckable(True)
        self.visM6.setObjectName("visM6")
        self.gridLayout_2.addWidget(self.visM6, 10, 9, 1, 1)
        self.visM3 = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visM3.sizePolicy().hasHeightForWidth())
        self.visM3.setSizePolicy(sizePolicy)
        self.visM3.setMinimumSize(QtCore.QSize(20, 30))
        self.visM3.setMaximumSize(QtCore.QSize(50, 50))
        self.visM3.setCheckable(True)
        self.visM3.setObjectName("visM3")
        self.gridLayout_2.addWidget(self.visM3, 9, 9, 1, 1)
        self.windM4 = QtWidgets.QToolButton(self.centralwidget)
        self.windM4.setMinimumSize(QtCore.QSize(20, 25))
        self.windM4.setMaximumSize(QtCore.QSize(50, 50))
        self.windM4.setCheckable(True)
        self.windM4.setObjectName("windM4")
        self.gridLayout_2.addWidget(self.windM4, 3, 9, 1, 1)
        self.cldS1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cldS1.sizePolicy().hasHeightForWidth())
        self.cldS1.setSizePolicy(sizePolicy)
        self.cldS1.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cldS1.setFont(font)
        self.cldS1.setText("")
        self.cldS1.setObjectName("cldS1")
        self.gridLayout_2.addWidget(self.cldS1, 5, 1, 1, 1)
        self.visS2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visS2.sizePolicy().hasHeightForWidth())
        self.visS2.setSizePolicy(sizePolicy)
        self.visS2.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.visS2.setFont(font)
        self.visS2.setText("")
        self.visS2.setObjectName("visS2")
        self.gridLayout_2.addWidget(self.visS2, 9, 6, 1, 1)
        self.windS2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windS2.sizePolicy().hasHeightForWidth())
        self.windS2.setSizePolicy(sizePolicy)
        self.windS2.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.windS2.setFont(font)
        self.windS2.setText("")
        self.windS2.setObjectName("windS2")
        self.gridLayout_2.addWidget(self.windS2, 1, 8, 1, 1)
        self.windS1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windS1.sizePolicy().hasHeightForWidth())
        self.windS1.setSizePolicy(sizePolicy)
        self.windS1.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.windS1.setFont(font)
        self.windS1.setText("")
        self.windS1.setObjectName("windS1")
        self.gridLayout_2.addWidget(self.windS1, 1, 4, 1, 1)
        self.windS3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windS3.sizePolicy().hasHeightForWidth())
        self.windS3.setSizePolicy(sizePolicy)
        self.windS3.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.windS3.setFont(font)
        self.windS3.setText("")
        self.windS3.setObjectName("windS3")
        self.gridLayout_2.addWidget(self.windS3, 3, 4, 1, 1)
        self.visS4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visS4.sizePolicy().hasHeightForWidth())
        self.visS4.setSizePolicy(sizePolicy)
        self.visS4.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.visS4.setFont(font)
        self.visS4.setText("")
        self.visS4.setObjectName("visS4")
        self.gridLayout_2.addWidget(self.visS4, 10, 4, 1, 1)
        self.visS1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visS1.sizePolicy().hasHeightForWidth())
        self.visS1.setSizePolicy(sizePolicy)
        self.visS1.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.visS1.setFont(font)
        self.visS1.setText("")
        self.visS1.setObjectName("visS1")
        self.gridLayout_2.addWidget(self.visS1, 9, 4, 1, 1)
        self.windS4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windS4.sizePolicy().hasHeightForWidth())
        self.windS4.setSizePolicy(sizePolicy)
        self.windS4.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.windS4.setFont(font)
        self.windS4.setText("")
        self.windS4.setObjectName("windS4")
        self.gridLayout_2.addWidget(self.windS4, 3, 8, 1, 1)
        self.visS3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visS3.sizePolicy().hasHeightForWidth())
        self.visS3.setSizePolicy(sizePolicy)
        self.visS3.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.visS3.setFont(font)
        self.visS3.setText("")
        self.visS3.setObjectName("visS3")
        self.gridLayout_2.addWidget(self.visS3, 9, 8, 1, 1)
        self.visS5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visS5.sizePolicy().hasHeightForWidth())
        self.visS5.setSizePolicy(sizePolicy)
        self.visS5.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.visS5.setFont(font)
        self.visS5.setText("")
        self.visS5.setObjectName("visS5")
        self.gridLayout_2.addWidget(self.visS5, 10, 6, 1, 1)
        self.visS6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visS6.sizePolicy().hasHeightForWidth())
        self.visS6.setSizePolicy(sizePolicy)
        self.visS6.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.visS6.setFont(font)
        self.visS6.setText("")
        self.visS6.setObjectName("visS6")
        self.gridLayout_2.addWidget(self.visS6, 10, 8, 1, 1)
        self.visM1 = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visM1.sizePolicy().hasHeightForWidth())
        self.visM1.setSizePolicy(sizePolicy)
        self.visM1.setMinimumSize(QtCore.QSize(20, 30))
        self.visM1.setMaximumSize(QtCore.QSize(50, 50))
        self.visM1.setCheckable(True)
        self.visM1.setObjectName("visM1")
        self.gridLayout_2.addWidget(self.visM1, 9, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 8, 1, 1, 10)
        spacerItem10 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 4, 1, 1, 11)
        spacerItem11 = QtWidgets.QSpacerItem(80, 60, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 0, 1, 1, 11)
        self.visM2 = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visM2.sizePolicy().hasHeightForWidth())
        self.visM2.setSizePolicy(sizePolicy)
        self.visM2.setMinimumSize(QtCore.QSize(20, 30))
        self.visM2.setMaximumSize(QtCore.QSize(50, 50))
        self.visM2.setCheckable(True)
        self.visM2.setObjectName("visM2")
        self.gridLayout_2.addWidget(self.visM2, 9, 7, 1, 1)
        self.windM1 = QtWidgets.QToolButton(self.centralwidget)
        self.windM1.setMinimumSize(QtCore.QSize(20, 25))
        self.windM1.setMaximumSize(QtCore.QSize(50, 50))
        self.windM1.setCheckable(True)
        self.windM1.setChecked(False)
        self.windM1.setObjectName("windM1")
        self.gridLayout_2.addWidget(self.windM1, 1, 3, 1, 1)
        self.windM3 = QtWidgets.QToolButton(self.centralwidget)
        self.windM3.setMinimumSize(QtCore.QSize(20, 25))
        self.windM3.setMaximumSize(QtCore.QSize(50, 50))
        self.windM3.setCheckable(True)
        self.windM3.setObjectName("windM3")
        self.gridLayout_2.addWidget(self.windM3, 3, 3, 1, 1)
        self.visM4 = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visM4.sizePolicy().hasHeightForWidth())
        self.visM4.setSizePolicy(sizePolicy)
        self.visM4.setMinimumSize(QtCore.QSize(20, 30))
        self.visM4.setMaximumSize(QtCore.QSize(50, 50))
        self.visM4.setCheckable(True)
        self.visM4.setObjectName("visM4")
        self.gridLayout_2.addWidget(self.visM4, 10, 3, 1, 1)
        self.cldS3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cldS3.sizePolicy().hasHeightForWidth())
        self.cldS3.setSizePolicy(sizePolicy)
        self.cldS3.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cldS3.setFont(font)
        self.cldS3.setText("")
        self.cldS3.setObjectName("cldS3")
        self.gridLayout_2.addWidget(self.cldS3, 6, 1, 1, 1)
        self.cldS2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cldS2.sizePolicy().hasHeightForWidth())
        self.cldS2.setSizePolicy(sizePolicy)
        self.cldS2.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cldS2.setFont(font)
        self.cldS2.setText("")
        self.cldS2.setObjectName("cldS2")
        self.gridLayout_2.addWidget(self.cldS2, 5, 10, 1, 1)
        self.windM2 = QtWidgets.QToolButton(self.centralwidget)
        self.windM2.setMinimumSize(QtCore.QSize(20, 25))
        self.windM2.setMaximumSize(QtCore.QSize(50, 50))
        self.windM2.setCheckable(True)
        self.windM2.setObjectName("windM2")
        self.gridLayout_2.addWidget(self.windM2, 1, 9, 1, 1)
        self.cldS4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cldS4.sizePolicy().hasHeightForWidth())
        self.cldS4.setSizePolicy(sizePolicy)
        self.cldS4.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cldS4.setFont(font)
        self.cldS4.setText("")
        self.cldS4.setObjectName("cldS4")
        self.gridLayout_2.addWidget(self.cldS4, 6, 10, 1, 1)
        self.cldM1 = QtWidgets.QToolButton(self.centralwidget)
        self.cldM1.setMinimumSize(QtCore.QSize(20, 25))
        self.cldM1.setMaximumSize(QtCore.QSize(50, 50))
        self.cldM1.setCheckable(True)
        self.cldM1.setObjectName("cldM1")
        self.gridLayout_2.addWidget(self.cldM1, 5, 3, 1, 1)
        self.cldM3 = QtWidgets.QToolButton(self.centralwidget)
        self.cldM3.setMinimumSize(QtCore.QSize(20, 25))
        self.cldM3.setMaximumSize(QtCore.QSize(50, 50))
        self.cldM3.setCheckable(True)
        self.cldM3.setObjectName("cldM3")
        self.gridLayout_2.addWidget(self.cldM3, 6, 3, 1, 1)
        self.cldM2 = QtWidgets.QToolButton(self.centralwidget)
        self.cldM2.setMinimumSize(QtCore.QSize(20, 25))
        self.cldM2.setMaximumSize(QtCore.QSize(50, 50))
        self.cldM2.setCheckable(True)
        self.cldM2.setObjectName("cldM2")
        self.gridLayout_2.addWidget(self.cldM2, 5, 9, 1, 1)
        self.cldM4 = QtWidgets.QToolButton(self.centralwidget)
        self.cldM4.setMinimumSize(QtCore.QSize(20, 25))
        self.cldM4.setMaximumSize(QtCore.QSize(50, 50))
        self.cldM4.setCheckable(True)
        self.cldM4.setObjectName("cldM4")
        self.gridLayout_2.addWidget(self.cldM4, 6, 9, 1, 1)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_2)
        spacerItem12 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.SpanningRole, spacerItem12)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.statusBar.setFont(font)
        self.statusBar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.statusBar.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.statusBar.setStatusTip("")
        self.statusBar.setWhatsThis("")
        self.statusBar.setAccessibleName("")
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1106, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menuLogs = QtWidgets.QMenu(self.menu)
        self.menuLogs.setObjectName("menuLogs")
        self.menuSett = QtWidgets.QMenu(self.menu)
        self.menuSett.setObjectName("menuSett")
        MainWindow.setMenuBar(self.menuBar)
        self.iram = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/icons8-settings-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.iram.setIcon(icon1)
        self.iram.setObjectName("iram")
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setObjectName("about")
        self.report = QtWidgets.QAction(MainWindow)
        self.report.setObjectName("report")
        self.log = QtWidgets.QAction(MainWindow)
        self.log.setObjectName("log")
        self.menuLogs.addAction(self.report)
        self.menuLogs.addAction(self.log)
        self.menuSett.addAction(self.iram)
        self.menu.addAction(self.menuSett.menuAction())
        self.menu.addAction(self.menuLogs.menuAction())
        self.menu.addAction(self.about)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.start, self.exit)
        MainWindow.setTabOrder(self.exit, self.btn)
        MainWindow.setTabOrder(self.btn, self.terminal)
        MainWindow.setTabOrder(self.terminal, self.windS1)
        MainWindow.setTabOrder(self.windS1, self.windS2)
        MainWindow.setTabOrder(self.windS2, self.windS3)
        MainWindow.setTabOrder(self.windS3, self.windS4)
        MainWindow.setTabOrder(self.windS4, self.cldS1)
        MainWindow.setTabOrder(self.cldS1, self.cldS2)
        MainWindow.setTabOrder(self.cldS2, self.cldS3)
        MainWindow.setTabOrder(self.cldS3, self.cldS4)
        MainWindow.setTabOrder(self.cldS4, self.visS1)
        MainWindow.setTabOrder(self.visS1, self.visS2)
        MainWindow.setTabOrder(self.visS2, self.visS3)
        MainWindow.setTabOrder(self.visS3, self.visS4)
        MainWindow.setTabOrder(self.visS4, self.visS5)
        MainWindow.setTabOrder(self.visS5, self.visS6)
        MainWindow.setTabOrder(self.visS6, self.windM1)
        MainWindow.setTabOrder(self.windM1, self.windM2)
        MainWindow.setTabOrder(self.windM2, self.windM3)
        MainWindow.setTabOrder(self.windM3, self.windM4)
        MainWindow.setTabOrder(self.windM4, self.visM1)
        MainWindow.setTabOrder(self.visM1, self.visM2)
        MainWindow.setTabOrder(self.visM2, self.visM3)
        MainWindow.setTabOrder(self.visM3, self.visM4)
        MainWindow.setTabOrder(self.visM4, self.visM5)
        MainWindow.setTabOrder(self.visM5, self.visM6)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Maintenance  UCFM"))
        self.btn.setText(_translate("MainWindow", "M"))
        self.terminal.setText(_translate("MainWindow", "TERMINAL"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.exit.setText(_translate("MainWindow", "Exit"))
        self.visV5.setToolTip(_translate("MainWindow", "LT5"))
        self.visV5.setText(_translate("MainWindow", "VIS5"))
        self.windV1.setToolTip(_translate("MainWindow", "WT1"))
        self.windV1.setText(_translate("MainWindow", "WIND1"))
        self.windV2.setToolTip(_translate("MainWindow", "WT3"))
        self.windV2.setText(_translate("MainWindow", "WIND2"))
        self.cldV3.setToolTip(_translate("MainWindow", "CL3"))
        self.cldV3.setText(_translate("MainWindow", "CLD3"))
        self.cldV2.setToolTip(_translate("MainWindow", "CL2"))
        self.cldV2.setText(_translate("MainWindow", "CLD2"))
        self.visV2.setToolTip(_translate("MainWindow", "LT2"))
        self.visV2.setText(_translate("MainWindow", "VIS2"))
        self.cldV4.setToolTip(_translate("MainWindow", "CL4"))
        self.cldV4.setText(_translate("MainWindow", "CLD4"))
        self.tempV2.setToolTip(_translate("MainWindow", "WT2"))
        self.tempV2.setText(_translate("MainWindow", "TEMP2"))
        self.windV3.setToolTip(_translate("MainWindow", "WT4"))
        self.windV3.setText(_translate("MainWindow", "WIND3"))
        self.mk2.setText(_translate("MainWindow", "MK255"))
        self.visV6.setToolTip(_translate("MainWindow", "LT6"))
        self.visV6.setText(_translate("MainWindow", "VIS6"))
        self.windV4.setToolTip(_translate("MainWindow", "WT6"))
        self.windV4.setText(_translate("MainWindow", "WIND4"))
        self.mk1.setText(_translate("MainWindow", "MK75"))
        self.cldV1.setToolTip(_translate("MainWindow", "CL1"))
        self.cldV1.setText(_translate("MainWindow", "CLD1"))
        self.visV4.setToolTip(_translate("MainWindow", "LT4"))
        self.visV4.setText(_translate("MainWindow", "VIS4"))
        self.visV3.setToolTip(_translate("MainWindow", "LT3"))
        self.visV3.setText(_translate("MainWindow", "VIS3"))
        self.visV1.setToolTip(_translate("MainWindow", "LT1"))
        self.visV1.setText(_translate("MainWindow", "VIS1"))
        self.tempV1.setToolTip(_translate("MainWindow", "WT1"))
        self.tempV1.setText(_translate("MainWindow", "TEMP1"))
        self.presV1.setToolTip(_translate("MainWindow", "WT1"))
        self.presV1.setText(_translate("MainWindow", "PRES1"))
        self.presV2.setToolTip(_translate("MainWindow", "WT2"))
        self.presV2.setText(_translate("MainWindow", "PRES2"))
        self.visM5.setText(_translate("MainWindow", "M"))
        self.visM6.setText(_translate("MainWindow", "M"))
        self.visM3.setText(_translate("MainWindow", "M"))
        self.windM4.setText(_translate("MainWindow", "M"))
        self.visM1.setText(_translate("MainWindow", "M"))
        self.visM2.setText(_translate("MainWindow", "M"))
        self.windM1.setText(_translate("MainWindow", "M"))
        self.windM3.setText(_translate("MainWindow", "M"))
        self.visM4.setText(_translate("MainWindow", "M"))
        self.windM2.setText(_translate("MainWindow", "M"))
        self.cldM1.setText(_translate("MainWindow", "M"))
        self.cldM3.setText(_translate("MainWindow", "M"))
        self.cldM2.setText(_translate("MainWindow", "M"))
        self.cldM4.setText(_translate("MainWindow", "M"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.menuLogs.setTitle(_translate("MainWindow", "LOGS"))
        self.menuSett.setTitle(_translate("MainWindow", "Настройки"))
        self.iram.setText(_translate("MainWindow", "IRAM"))
        self.about.setText(_translate("MainWindow", "About"))
        self.report.setText(_translate("MainWindow", "Report"))
        self.log.setText(_translate("MainWindow", "Log"))


