# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MaintSettings_design.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(731, 831)
        Settings.setMaximumSize(QtCore.QSize(731, 831))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/icons/icons8-settings-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Settings.setWindowIcon(icon)
        Settings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gridLayout_2 = QtWidgets.QGridLayout(Settings)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(Settings)
        self.label_3.setMinimumSize(QtCore.QSize(180, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sens_viewBr = QtWidgets.QTextBrowser(Settings)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.sens_viewBr.setFont(font)
        self.sens_viewBr.setObjectName("sens_viewBr")
        self.horizontalLayout_3.addWidget(self.sens_viewBr)
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout, 7, 1, 1, 1)
        self.label_0 = QtWidgets.QLabel(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_0.sizePolicy().hasHeightForWidth())
        self.label_0.setSizePolicy(sizePolicy)
        self.label_0.setMinimumSize(QtCore.QSize(180, 0))
        self.label_0.setMaximumSize(QtCore.QSize(500, 30))
        self.label_0.setObjectName("label_0")
        self.gridLayout.addWidget(self.label_0, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.av6_pathLn = QtWidgets.QLineEdit(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.av6_pathLn.sizePolicy().hasHeightForWidth())
        self.av6_pathLn.setSizePolicy(sizePolicy)
        self.av6_pathLn.setMinimumSize(QtCore.QSize(0, 20))
        self.av6_pathLn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.av6_pathLn.setObjectName("av6_pathLn")
        self.horizontalLayout_5.addWidget(self.av6_pathLn, 0, QtCore.Qt.AlignLeft)
        self.label = QtWidgets.QLabel(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label, 0, QtCore.Qt.AlignLeft)
        self.av6_time1Ln = QtWidgets.QLineEdit(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.av6_time1Ln.sizePolicy().hasHeightForWidth())
        self.av6_time1Ln.setSizePolicy(sizePolicy)
        self.av6_time1Ln.setMinimumSize(QtCore.QSize(0, 20))
        self.av6_time1Ln.setObjectName("av6_time1Ln")
        self.horizontalLayout_5.addWidget(self.av6_time1Ln, 0, QtCore.Qt.AlignLeft)
        self.av6_time2Ln = QtWidgets.QLineEdit(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.av6_time2Ln.sizePolicy().hasHeightForWidth())
        self.av6_time2Ln.setSizePolicy(sizePolicy)
        self.av6_time2Ln.setMinimumSize(QtCore.QSize(0, 20))
        self.av6_time2Ln.setObjectName("av6_time2Ln")
        self.horizontalLayout_5.addWidget(self.av6_time2Ln, 0, QtCore.Qt.AlignLeft)
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_8 = QtWidgets.QLabel(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(110, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.av6_writeCh = QtWidgets.QCheckBox(Settings)
        self.av6_writeCh.setMinimumSize(QtCore.QSize(0, 15))
        self.av6_writeCh.setText("")
        self.av6_writeCh.setObjectName("av6_writeCh")
        self.horizontalLayout_5.addWidget(self.av6_writeCh, 0, QtCore.Qt.AlignRight)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Settings)
        self.label_4.setMinimumSize(QtCore.QSize(180, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.label_1 = QtWidgets.QLabel(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1.sizePolicy().hasHeightForWidth())
        self.label_1.setSizePolicy(sizePolicy)
        self.label_1.setMinimumSize(QtCore.QSize(180, 0))
        self.label_1.setMaximumSize(QtCore.QSize(500, 30))
        self.label_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.refresh_timeLn = QtWidgets.QLineEdit(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refresh_timeLn.sizePolicy().hasHeightForWidth())
        self.refresh_timeLn.setSizePolicy(sizePolicy)
        self.refresh_timeLn.setMinimumSize(QtCore.QSize(40, 15))
        self.refresh_timeLn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.refresh_timeLn.setObjectName("refresh_timeLn")
        self.horizontalLayout_8.addWidget(self.refresh_timeLn, 0, QtCore.Qt.AlignLeft)
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.label_6 = QtWidgets.QLabel(Settings)
        self.label_6.setMinimumSize(QtCore.QSize(110, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.mserialCh = QtWidgets.QCheckBox(Settings)
        self.mserialCh.setEnabled(True)
        self.mserialCh.setMinimumSize(QtCore.QSize(0, 15))
        self.mserialCh.setText("")
        self.mserialCh.setCheckable(True)
        self.mserialCh.setChecked(False)
        self.mserialCh.setTristate(False)
        self.mserialCh.setObjectName("mserialCh")
        self.horizontalLayout_8.addWidget(self.mserialCh, 0, QtCore.Qt.AlignRight)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout_8, 4, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.f_waitLn = QtWidgets.QLineEdit(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_waitLn.sizePolicy().hasHeightForWidth())
        self.f_waitLn.setSizePolicy(sizePolicy)
        self.f_waitLn.setMinimumSize(QtCore.QSize(40, 15))
        self.f_waitLn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.f_waitLn.setObjectName("f_waitLn")
        self.horizontalLayout_7.addWidget(self.f_waitLn, 0, QtCore.Qt.AlignLeft)
        spacerItem8 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        spacerItem10 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.label_5 = QtWidgets.QLabel(Settings)
        self.label_5.setMinimumSize(QtCore.QSize(110, 0))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.rep_writeCh = QtWidgets.QCheckBox(Settings)
        self.rep_writeCh.setMinimumSize(QtCore.QSize(0, 15))
        self.rep_writeCh.setText("")
        self.rep_writeCh.setObjectName("rep_writeCh")
        self.horizontalLayout_7.addWidget(self.rep_writeCh, 0, QtCore.Qt.AlignRight)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.gridLayout.addLayout(self.horizontalLayout_7, 3, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stationLb = QtWidgets.QLabel(Settings)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.stationLb.setFont(font)
        self.stationLb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stationLb.setText("")
        self.stationLb.setAlignment(QtCore.Qt.AlignCenter)
        self.stationLb.setObjectName("stationLb")
        self.horizontalLayout_4.addWidget(self.stationLb)
        self.stationBx = QtWidgets.QComboBox(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stationBx.sizePolicy().hasHeightForWidth())
        self.stationBx.setSizePolicy(sizePolicy)
        self.stationBx.setObjectName("stationBx")
        self.horizontalLayout_4.addWidget(self.stationBx)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Settings)
        self.label_2.setMinimumSize(QtCore.QSize(180, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.sens_pathLn = QtWidgets.QLineEdit(Settings)
        self.sens_pathLn.setMinimumSize(QtCore.QSize(0, 15))
        self.sens_pathLn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.sens_pathLn.setObjectName("sens_pathLn")
        self.gridLayout.addWidget(self.sens_pathLn, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sens_addBx = QtWidgets.QComboBox(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sens_addBx.sizePolicy().hasHeightForWidth())
        self.sens_addBx.setSizePolicy(sizePolicy)
        self.sens_addBx.setMinimumSize(QtCore.QSize(80, 0))
        self.sens_addBx.setObjectName("sens_addBx")
        self.horizontalLayout_2.addWidget(self.sens_addBx)
        spacerItem13 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.sens_addLn = QtWidgets.QLineEdit(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sens_addLn.sizePolicy().hasHeightForWidth())
        self.sens_addLn.setSizePolicy(sizePolicy)
        self.sens_addLn.setMinimumSize(QtCore.QSize(80, 15))
        self.sens_addLn.setObjectName("sens_addLn")
        self.horizontalLayout_2.addWidget(self.sens_addLn)
        self.sens_addBt = QtWidgets.QPushButton(Settings)
        self.sens_addBt.setObjectName("sens_addBt")
        self.horizontalLayout_2.addWidget(self.sens_addBt)
        spacerItem14 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem14)
        spacerItem15 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem15)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(180, 0))
        self.label_7.setMaximumSize(QtCore.QSize(500, 30))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.sound_pathLn = QtWidgets.QLineEdit(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sound_pathLn.sizePolicy().hasHeightForWidth())
        self.sound_pathLn.setSizePolicy(sizePolicy)
        self.sound_pathLn.setMinimumSize(QtCore.QSize(270, 15))
        self.sound_pathLn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.sound_pathLn.setObjectName("sound_pathLn")
        self.horizontalLayout_9.addWidget(self.sound_pathLn)
        self.sound_testBt = QtWidgets.QToolButton(Settings)
        self.sound_testBt.setMinimumSize(QtCore.QSize(50, 20))
        self.sound_testBt.setObjectName("sound_testBt")
        self.horizontalLayout_9.addWidget(self.sound_testBt)
        spacerItem16 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem16)
        spacerItem17 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem17)
        spacerItem18 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem18)
        self.gridLayout.addLayout(self.horizontalLayout_9, 2, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem19, 6, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.buttHelp = QtWidgets.QPushButton(Settings)
        self.buttHelp.setObjectName("buttHelp")
        self.gridLayout_2.addWidget(self.buttHelp, 1, 0, 1, 1)
        self.buttOK = QtWidgets.QDialogButtonBox(Settings)
        self.buttOK.setMaximumSize(QtCore.QSize(630, 23))
        self.buttOK.setFocusPolicy(QtCore.Qt.TabFocus)
        self.buttOK.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttOK.setCenterButtons(False)
        self.buttOK.setObjectName("buttOK")
        self.gridLayout_2.addWidget(self.buttOK, 1, 1, 1, 1)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)
        Settings.setTabOrder(self.buttOK, self.sens_pathLn)
        Settings.setTabOrder(self.sens_pathLn, self.sens_addLn)
        Settings.setTabOrder(self.sens_addLn, self.sens_addBt)
        Settings.setTabOrder(self.sens_addBt, self.sens_viewBr)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Настройки"))
        self.label_3.setText(_translate("Settings", "Время ожидания файла (мин)"))
        self.label_0.setText(_translate("Settings", "Выбор Станции"))
        self.label.setText(_translate("Settings", "Время записи АВ-6"))
        self.label_8.setText(_translate("Settings", "Запись АВ-6"))
        self.label_4.setText(_translate("Settings", "Время обновления опроса (мсек)"))
        self.label_1.setText(_translate("Settings", "Путь к папке IRAM"))
        self.label_6.setText(_translate("Settings", "Mserial"))
        self.label_5.setText(_translate("Settings", "Запись Report файла"))
        self.label_2.setText(_translate("Settings", "Путь к WAV файлу"))
        self.sens_addBt.setText(_translate("Settings", "Добавить"))
        self.label_7.setText(_translate("Settings", "Путь к архиву АВ-6"))
        self.sound_testBt.setText(_translate("Settings", "TEST"))
        self.buttHelp.setText(_translate("Settings", "Help"))


