# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mserial_design.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(556, 335)
        MainWindow.setMinimumSize(QtCore.QSize(556, 335))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.sensButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.sensButton3.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.sensButton3.setFont(font)
        self.sensButton3.setText("")
        self.sensButton3.setObjectName("sensButton3")
        self.gridLayout.addWidget(self.sensButton3, 3, 2, 1, 1)
        self.comBrowser2 = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setBold(True)
        font.setWeight(75)
        self.comBrowser2.setFont(font)
        self.comBrowser2.setObjectName("comBrowser2")
        self.gridLayout.addWidget(self.comBrowser2, 2, 4, 1, 3)
        self.comBox3 = QtWidgets.QComboBox(self.centralwidget)
        self.comBox3.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comBox3.setFont(font)
        self.comBox3.setObjectName("comBox3")
        self.gridLayout.addWidget(self.comBox3, 3, 1, 1, 1)
        self.comBox4 = QtWidgets.QComboBox(self.centralwidget)
        self.comBox4.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comBox4.setFont(font)
        self.comBox4.setObjectName("comBox4")
        self.gridLayout.addWidget(self.comBox4, 3, 4, 1, 1)
        self.sensButton4 = QtWidgets.QPushButton(self.centralwidget)
        self.sensButton4.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.sensButton4.setFont(font)
        self.sensButton4.setText("")
        self.sensButton4.setObjectName("sensButton4")
        self.gridLayout.addWidget(self.sensButton4, 3, 5, 1, 1)
        self.comBrowser4 = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setBold(True)
        font.setWeight(75)
        self.comBrowser4.setFont(font)
        self.comBrowser4.setObjectName("comBrowser4")
        self.gridLayout.addWidget(self.comBrowser4, 4, 4, 1, 3)
        self.comBrowser3 = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setBold(True)
        font.setWeight(75)
        self.comBrowser3.setFont(font)
        self.comBrowser3.setObjectName("comBrowser3")
        self.gridLayout.addWidget(self.comBrowser3, 4, 1, 1, 3)
        self.sensButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.sensButton1.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.sensButton1.setFont(font)
        self.sensButton1.setText("")
        self.sensButton1.setObjectName("sensButton1")
        self.gridLayout.addWidget(self.sensButton1, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.comBox2 = QtWidgets.QComboBox(self.centralwidget)
        self.comBox2.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comBox2.setFont(font)
        self.comBox2.setObjectName("comBox2")
        self.gridLayout.addWidget(self.comBox2, 0, 4, 1, 1)
        self.sensButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.sensButton2.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.sensButton2.setFont(font)
        self.sensButton2.setText("")
        self.sensButton2.setObjectName("sensButton2")
        self.gridLayout.addWidget(self.sensButton2, 0, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 6, 1, 1)
        self.comBrowser1 = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setBold(True)
        font.setWeight(75)
        self.comBrowser1.setFont(font)
        self.comBrowser1.setObjectName("comBrowser1")
        self.gridLayout.addWidget(self.comBrowser1, 2, 1, 1, 3)
        self.comBox1 = QtWidgets.QComboBox(self.centralwidget)
        self.comBox1.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comBox1.setFont(font)
        self.comBox1.setObjectName("comBox1")
        self.gridLayout.addWidget(self.comBox1, 0, 1, 1, 1)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setSizeIncrement(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 5, 6, 1, 1)
        self.statBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statBrowser.sizePolicy().hasHeightForWidth())
        self.statBrowser.setSizePolicy(sizePolicy)
        self.statBrowser.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setBold(True)
        font.setWeight(75)
        self.statBrowser.setFont(font)
        self.statBrowser.setObjectName("statBrowser")
        self.gridLayout.addWidget(self.statBrowser, 5, 1, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 556, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.actSettings = QtWidgets.QAction(MainWindow)
        self.actSettings.setObjectName("actSettings")
        self.menuMenu.addAction(self.actSettings)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mserial"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actSettings.setText(_translate("MainWindow", "Настройки"))


